name: Quality assurance PHP

on: ['pull_requests', 'push', 'workflow_dispatch']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-php:
    uses: inpsyde/reusable-workflows/.github/workflows/lint-php.yml@main
    with:
      PHP_MATRIX: '["7.2", "7.3", "7.4", "8.0", "8.1", "8.2"]'

  coding-standards-analysis-php:
    needs: lint-php
    uses: inpsyde/reusable-workflows/.github/workflows/coding-standards-php.yml@main
    with:
      PHPCS_ARGS: '--report=summary'

  static-analysis-php:
    needs: lint-php
    uses: inpsyde/reusable-workflows/.github/workflows/static-analysis-php.yml@main
